### PR TITLE
Final version for TWP!

### PR DESCRIPTION
**Pull request by twpierson**

### CODE REVIEW

**Comment by bomeara** [comment]
It's a bit odd that you have a different study id and tree id

**Comment by twpierson** [comment]
Do you mean the following bit?: 

`anolis.study1.tree1 <- get_study_tree(study_id=anolis.studies[[1]],tree_id=anolis.studies[[3]])` 

I'm calling the first object in the list `anolis.studies`, which is the `study_id`, and then the third object, which is the `tree_id`. But maybe I goofed.

**Comment by bomeara** [comment]
Look at the solutions; also note that rotl has recently changed.

**Comment by twpierson** [comment]
Hmm. I recognize that the .solutions.R file has a different solution, but I still don't think mine is wrong. In my version, I'm calling the `study_id` and `tree_id` objects specifically and individually, while in yours, the command is reading them by default from a list that contains both. We get the same answer. Anyway, maybe we can go over this better in class!

**Pull request closed without merging**
